### PR TITLE
v2.0

### PR DESCRIPTION
**Pull request by grunka**
A bunch of cleanups and updates, possibly some performance improvements

### CODE REVIEW

**Comment by Eyremba** [comment]
When will this be released?

**Comment by grunka** [comment]
I don't really remember why I didn't release it when doing the changes. I'll have a look at my notes and see if there was something that didn't get done.

**Comment by chrisnew** [comment]
Can you take my suggestion into account as well? I needed a way to shutdown Fortuna and cleanup the executors. :)

**Comment by grunka** [comment]
Definitely, I don't see a problem with adding that

**Comment by chrisnew** [comment]
Awesome! Thanks! :)

**Comment by Eyremba** [comment]
Nice!! Thanks! :) 👍

**Comment by Eyremba** [comment]
When will this finally get merged?!
Still waiting since last year. :D

**Comment by grunka** [comment]
I think right about now is good 😄

**Pull request merged**
